export const types = {
  HANDLE_CHANGE: "HANDLE_CHANGE",
  INIT_IMAGE: "INIT_IMAGE",
  UPDATE_STATE: "UPDATE_STATE",
  STORE_PARAMETERS: "STORE_PARAMETERS",
  STORE_SCALE_PARAMS: "STORE_SCALE_PARAMS",
  ADD_EFFECT: "ADD_EFFECT",
  ZOOM_IN: "ZOOM_IN",
  ZOOM_OUT: "ZOOM_OUT",
  UNDO: "UNDO",
  RESET: "RESET",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_ALL_ITEM: "REMOVE_ALL_ITEM"
};
